server:
  port: 7090
  servlet:
    context-path: /auth

jwt:
  auth:
    converter:
      resource-id: authenticationClientId
keycloak:
   realm: bisky-music
   adminClientId: admin-cli
   adminClientSecret: Ep6uxiU983scb4IqGeUIrqOzr4pg2UhM
   client: authenticationClientId
   urls:
       auth: http://localhost:9082
spring:
  profiles:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9082/realms/bisky-music
